<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>GVA.HMI.Example.Application</RootNamespace>
    <AssemblyName>GVA.HMI.Example.Application</AssemblyName>
    <UseWindowsForms>false</UseWindowsForms>
    <EnableDefaultApplicationDefinition>true</EnableDefaultApplicationDefinition>
  </PropertyGroup>

</Project>
